<?php

namespace ContainerRx9QPRa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kyw_RJSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kyw.RJS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kyw.RJS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctorRepo' => ['privates', 'App\\Repository\\DoctorRepository', 'getDoctorRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'doctorRepo' => 'App\\Repository\\DoctorRepository',
            'doctrine' => '?',
            'em' => '?',
            'passwordHasher' => '?',
        ]);
    }
}
