<?php

namespace ContainerCP9PnEZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8JWidSUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8JWidSU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8JWidSU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctorRepository' => ['privates', 'App\\Repository\\DoctorRepository', 'getDoctorRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'doctorRepository' => 'App\\Repository\\DoctorRepository',
            'em' => '?',
        ]);
    }
}
