<?php

namespace ContainerCP9PnEZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSlotGeneratorServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SlotGeneratorService' shared autowired service.
     *
     * @return \App\Service\SlotGeneratorService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SlotGeneratorService.php';

        return $container->privates['App\\Service\\SlotGeneratorService'] = new \App\Service\SlotGeneratorService();
    }
}
