<?php

namespace Container4hVBvVQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K58hXLZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k58hXLZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k58hXLZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'alarmRepository' => ['privates', 'App\\Repository\\AlarmRepository', 'getAlarmRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'alarmRepository' => 'App\\Repository\\AlarmRepository',
            'em' => '?',
        ]);
    }
}
