<?php

namespace Container6HepzCE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OuSGbL3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OuSGbL3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OuSGbL3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'slotGenerator' => ['privates', 'App\\Service\\SlotGeneratorService', 'getSlotGeneratorServiceService', true],
        ], [
            'em' => '?',
            'slotGenerator' => 'App\\Service\\SlotGeneratorService',
        ]);
    }
}
