<?php

namespace ContainerLTZ35Go;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NcuyKjXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ncuyKjX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ncuyKjX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctor' => ['privates', '.errored..service_locator.ncuyKjX.App\\Entity\\Doctor', NULL, 'Cannot autowire service ".service_locator.ncuyKjX": it references class "App\\Entity\\Doctor" but no such service exists.'],
            'slotService' => ['privates', 'App\\Service\\SlotGeneratorService', 'getSlotGeneratorServiceService', true],
        ], [
            'doctor' => 'App\\Entity\\Doctor',
            'slotService' => 'App\\Service\\SlotGeneratorService',
        ]);
    }
}
