<?php

namespace ContainerPmq0mWs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Orm_ContainerRepositoryFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'doctrine.orm.container_repository_factory' shared service.
     *
     * @return \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'doctrine'.\DIRECTORY_SEPARATOR.'orm'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'RepositoryFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'doctrine'.\DIRECTORY_SEPARATOR.'doctrine-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'RepositoryFactoryCompatibility.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'doctrine'.\DIRECTORY_SEPARATOR.'doctrine-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'ContainerRepositoryFactory.php';

        return $container->privates['doctrine.orm.container_repository_factory'] = new \Doctrine\Bundle\DoctrineBundle\Repository\ContainerRepositoryFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Repository\\AlarmRepository' => ['privates', 'App\\Repository\\AlarmRepository', 'getAlarmRepositoryService', true],
            'App\\Repository\\AppointmentRepository' => ['privates', 'App\\Repository\\AppointmentRepository', 'getAppointmentRepositoryService', true],
            'App\\Repository\\AvailabilityRepository' => ['privates', 'App\\Repository\\AvailabilityRepository', 'getAvailabilityRepositoryService', true],
            'App\\Repository\\CenterRepository' => ['privates', 'App\\Repository\\CenterRepository', 'getCenterRepositoryService', true],
            'App\\Repository\\DoctorRepository' => ['privates', 'App\\Repository\\DoctorRepository', 'getDoctorRepositoryService', true],
            'App\\Repository\\PatientRepository' => ['privates', 'App\\Repository\\PatientRepository', 'getPatientRepositoryService', true],
            'App\\Repository\\PaymentRepository' => ['privates', 'App\\Repository\\PaymentRepository', 'getPaymentRepositoryService', true],
            'App\\Repository\\PrescriptionRepository' => ['privates', 'App\\Repository\\PrescriptionRepository', 'getPrescriptionRepositoryService', true],
            'App\\Repository\\TreatmentRepository' => ['privates', 'App\\Repository\\TreatmentRepository', 'getTreatmentRepositoryService', true],
        ], [
            'App\\Repository\\AlarmRepository' => '?',
            'App\\Repository\\AppointmentRepository' => '?',
            'App\\Repository\\AvailabilityRepository' => '?',
            'App\\Repository\\CenterRepository' => '?',
            'App\\Repository\\DoctorRepository' => '?',
            'App\\Repository\\PatientRepository' => '?',
            'App\\Repository\\PaymentRepository' => '?',
            'App\\Repository\\PrescriptionRepository' => '?',
            'App\\Repository\\TreatmentRepository' => '?',
        ]));
    }
}
