<?php

namespace ContainerC7BvTqX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppointmentSlotControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AppointmentSlotController' shared autowired service.
     *
     * @return \App\Controller\AppointmentSlotController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AppointmentSlotController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SlotGeneratorService.php';

        $container->services['App\\Controller\\AppointmentSlotController'] = $instance = new \App\Controller\AppointmentSlotController(($container->privates['App\\Service\\SlotGeneratorService'] ?? ($container->privates['App\\Service\\SlotGeneratorService'] = new \App\Service\SlotGeneratorService())));

        $instance->setContainer(($container->privates['.service_locator.l1ae.Qz'] ?? $container->load('get_ServiceLocator_L1ae_QzService'))->withContext('App\\Controller\\AppointmentSlotController', $container));

        return $instance;
    }
}
