<?php

namespace ContainerYPu9JDS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XoTSmqPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XoTSmqP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XoTSmqP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\HealthNorthController::createPayment' => ['privates', '.service_locator.H2jV.2L', 'get_ServiceLocator_H2jV_2LService', true],
            'App\\Controller\\HealthNorthController::deletePayment' => ['privates', '.service_locator.CJtuRdo', 'get_ServiceLocator_CJtuRdoService', true],
            'App\\Controller\\HealthNorthController::getPatient' => ['privates', '.service_locator.8tq73hJ', 'get_ServiceLocator_8tq73hJService', true],
            'App\\Controller\\HealthNorthController::getPatientList' => ['privates', '.service_locator.8tq73hJ', 'get_ServiceLocator_8tq73hJService', true],
            'App\\Controller\\HealthNorthController::getPatientName' => ['privates', '.service_locator.8tq73hJ', 'get_ServiceLocator_8tq73hJService', true],
            'App\\Controller\\HealthNorthController::getPayment' => ['privates', '.service_locator.Yy3Z6z_', 'get_ServiceLocator_Yy3Z6zService', true],
            'App\\Controller\\HealthNorthController::updatePayment' => ['privates', '.service_locator..9EDVyX', 'get_ServiceLocator__9EDVyXService', true],
            'App\\Controller\\PatientController::me' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\PatientController::update' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\HealthNorthController:createPayment' => ['privates', '.service_locator.H2jV.2L', 'get_ServiceLocator_H2jV_2LService', true],
            'App\\Controller\\HealthNorthController:deletePayment' => ['privates', '.service_locator.CJtuRdo', 'get_ServiceLocator_CJtuRdoService', true],
            'App\\Controller\\HealthNorthController:getPatient' => ['privates', '.service_locator.8tq73hJ', 'get_ServiceLocator_8tq73hJService', true],
            'App\\Controller\\HealthNorthController:getPatientList' => ['privates', '.service_locator.8tq73hJ', 'get_ServiceLocator_8tq73hJService', true],
            'App\\Controller\\HealthNorthController:getPatientName' => ['privates', '.service_locator.8tq73hJ', 'get_ServiceLocator_8tq73hJService', true],
            'App\\Controller\\HealthNorthController:getPayment' => ['privates', '.service_locator.Yy3Z6z_', 'get_ServiceLocator_Yy3Z6zService', true],
            'App\\Controller\\HealthNorthController:updatePayment' => ['privates', '.service_locator..9EDVyX', 'get_ServiceLocator__9EDVyXService', true],
            'App\\Controller\\PatientController:me' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\PatientController:update' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\HealthNorthController::createPayment' => '?',
            'App\\Controller\\HealthNorthController::deletePayment' => '?',
            'App\\Controller\\HealthNorthController::getPatient' => '?',
            'App\\Controller\\HealthNorthController::getPatientList' => '?',
            'App\\Controller\\HealthNorthController::getPatientName' => '?',
            'App\\Controller\\HealthNorthController::getPayment' => '?',
            'App\\Controller\\HealthNorthController::updatePayment' => '?',
            'App\\Controller\\PatientController::me' => '?',
            'App\\Controller\\PatientController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\HealthNorthController:createPayment' => '?',
            'App\\Controller\\HealthNorthController:deletePayment' => '?',
            'App\\Controller\\HealthNorthController:getPatient' => '?',
            'App\\Controller\\HealthNorthController:getPatientList' => '?',
            'App\\Controller\\HealthNorthController:getPatientName' => '?',
            'App\\Controller\\HealthNorthController:getPayment' => '?',
            'App\\Controller\\HealthNorthController:updatePayment' => '?',
            'App\\Controller\\PatientController:me' => '?',
            'App\\Controller\\PatientController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
