<?php

namespace ContainerXM73SO5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yy3Z6zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Yy3Z6z_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Yy3Z6z_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paymentRepository' => ['privates', 'App\\Repository\\PaymentRepository', 'getPaymentRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'paymentRepository' => 'App\\Repository\\PaymentRepository',
            'serializer' => '?',
        ]);
    }
}
