<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Patient extends \App\Entity\Patient implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'firstname', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'lastname', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'postalAddress', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'socialsecurityNumber', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'phoneNumber', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'picture', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'socialsecurityRegime', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'healthcareInsurance', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'allergy', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'medicalTraitmentDisease', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'medicalHistory', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'emergencyContact', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'doctor', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'option', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'payments', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'appointments', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'alarms', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'documents'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'firstname', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'lastname', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'postalAddress', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'socialsecurityNumber', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'phoneNumber', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'picture', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'socialsecurityRegime', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'healthcareInsurance', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'allergy', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'medicalTraitmentDisease', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'medicalHistory', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'emergencyContact', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'doctor', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'option', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'payments', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'appointments', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'alarms', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'documents'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Patient $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', []);

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname(?string $firstname): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', [$firstname]);

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', []);

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname(?string $lastname): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', [$lastname]);

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(?string $email): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(?string $password): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalAddress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalAddress', []);

        return parent::getPostalAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalAddress(?string $postalAddress): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalAddress', [$postalAddress]);

        return parent::setPostalAddress($postalAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getSocialsecurityNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSocialsecurityNumber', []);

        return parent::getSocialsecurityNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setSocialsecurityNumber(?string $socialSecurityNumber): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSocialsecurityNumber', [$socialSecurityNumber]);

        return parent::setSocialsecurityNumber($socialSecurityNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', []);

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber(?string $phoneNumber): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', [$phoneNumber]);

        return parent::setPhoneNumber($phoneNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPicture(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicture', []);

        return parent::getPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setPicture(?string $picture): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicture', [$picture]);

        return parent::setPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getSocialsecurityRegime(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSocialsecurityRegime', []);

        return parent::getSocialsecurityRegime();
    }

    /**
     * {@inheritDoc}
     */
    public function setSocialsecurityRegime(?string $socialsecurityRegime): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSocialsecurityRegime', [$socialsecurityRegime]);

        return parent::setSocialsecurityRegime($socialsecurityRegime);
    }

    /**
     * {@inheritDoc}
     */
    public function getHealthcareInsurance(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHealthcareInsurance', []);

        return parent::getHealthcareInsurance();
    }

    /**
     * {@inheritDoc}
     */
    public function setHealthcareInsurance(?string $healthcareInsurance): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHealthcareInsurance', [$healthcareInsurance]);

        return parent::setHealthcareInsurance($healthcareInsurance);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllergy(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllergy', []);

        return parent::getAllergy();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllergy(?string $allergy): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllergy', [$allergy]);

        return parent::setAllergy($allergy);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedicalTraitmentDisease(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedicalTraitmentDisease', []);

        return parent::getMedicalTraitmentDisease();
    }

    /**
     * {@inheritDoc}
     */
    public function setMedicalTraitmentDisease(?string $medicalTraitmentDisease): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedicalTraitmentDisease', [$medicalTraitmentDisease]);

        return parent::setMedicalTraitmentDisease($medicalTraitmentDisease);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedicalHistory(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedicalHistory', []);

        return parent::getMedicalHistory();
    }

    /**
     * {@inheritDoc}
     */
    public function setMedicalHistory(?string $medicalHistory): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedicalHistory', [$medicalHistory]);

        return parent::setMedicalHistory($medicalHistory);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmergencyContact(): ?\App\Entity\EmergencyContact
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmergencyContact', []);

        return parent::getEmergencyContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmergencyContact(?\App\Entity\EmergencyContact $emergencyContact): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmergencyContact', [$emergencyContact]);

        return parent::setEmergencyContact($emergencyContact);
    }

    /**
     * {@inheritDoc}
     */
    public function getDoctor(): ?\App\Entity\Doctor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoctor', []);

        return parent::getDoctor();
    }

    /**
     * {@inheritDoc}
     */
    public function setDoctor(?\App\Entity\Doctor $doctor): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoctor', [$doctor]);

        return parent::setDoctor($doctor);
    }

    /**
     * {@inheritDoc}
     */
    public function getOption(): ?\App\Entity\Option
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOption', []);

        return parent::getOption();
    }

    /**
     * {@inheritDoc}
     */
    public function setOption(?\App\Entity\Option $option): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOption', [$option]);

        return parent::setOption($option);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserIdentifier(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserIdentifier', []);

        return parent::getUserIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getPayments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayments', []);

        return parent::getPayments();
    }

    /**
     * {@inheritDoc}
     */
    public function addPayment(\App\Entity\Payment $payment): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPayment', [$payment]);

        return parent::addPayment($payment);
    }

    /**
     * {@inheritDoc}
     */
    public function removePayment(\App\Entity\Payment $payment): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePayment', [$payment]);

        return parent::removePayment($payment);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppointments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppointments', []);

        return parent::getAppointments();
    }

    /**
     * {@inheritDoc}
     */
    public function getAlarms(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlarms', []);

        return parent::getAlarms();
    }

    /**
     * {@inheritDoc}
     */
    public function getDocuments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocuments', []);

        return parent::getDocuments();
    }

}
