<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Treatment extends \App\Entity\Treatment implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'paid', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'attendingPhysician', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'patient', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'appointment', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'medicines', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'prescriptions'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'paid', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'attendingPhysician', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'patient', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'appointment', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'medicines', '' . "\0" . 'App\\Entity\\Treatment' . "\0" . 'prescriptions'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Treatment $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(?string $name): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(?int $price): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function isPaid(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPaid', []);

        return parent::isPaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaid(?bool $paid): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaid', [$paid]);

        return parent::setPaid($paid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttendingPhysician(): ?\App\Entity\Doctor
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttendingPhysician', []);

        return parent::getAttendingPhysician();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttendingPhysician(?\App\Entity\Doctor $doctor): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttendingPhysician', [$doctor]);

        return parent::setAttendingPhysician($doctor);
    }

    /**
     * {@inheritDoc}
     */
    public function getPatient(): ?\App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatient', []);

        return parent::getPatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setPatient(?\App\Entity\Patient $patient): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatient', [$patient]);

        return parent::setPatient($patient);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedicine(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedicine', []);

        return parent::getMedicine();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrescriptions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrescriptions', []);

        return parent::getPrescriptions();
    }

    /**
     * {@inheritDoc}
     */
    public function getAppointment(): ?\App\Entity\Appointment
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppointment', []);

        return parent::getAppointment();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppointment(?\App\Entity\Appointment $appointment): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppointment', [$appointment]);

        return parent::setAppointment($appointment);
    }

}
