<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Option extends \App\Entity\Option implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Option' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Option' . "\0" . 'communicationForm', '' . "\0" . 'App\\Entity\\Option' . "\0" . 'privateRoom', '' . "\0" . 'App\\Entity\\Option' . "\0" . 'television', '' . "\0" . 'App\\Entity\\Option' . "\0" . 'wifi', '' . "\0" . 'App\\Entity\\Option' . "\0" . 'diet', '' . "\0" . 'App\\Entity\\Option' . "\0" . 'patients'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Option' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Option' . "\0" . 'communicationForm', '' . "\0" . 'App\\Entity\\Option' . "\0" . 'privateRoom', '' . "\0" . 'App\\Entity\\Option' . "\0" . 'television', '' . "\0" . 'App\\Entity\\Option' . "\0" . 'wifi', '' . "\0" . 'App\\Entity\\Option' . "\0" . 'diet', '' . "\0" . 'App\\Entity\\Option' . "\0" . 'patients'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Option $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCommunicationForm(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommunicationForm', []);

        return parent::getCommunicationForm();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommunicationForm(?string $communicationForm): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommunicationForm', [$communicationForm]);

        return parent::setCommunicationForm($communicationForm);
    }

    /**
     * {@inheritDoc}
     */
    public function isPrivateRoom(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPrivateRoom', []);

        return parent::isPrivateRoom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrivateRoom(?bool $privateRoom): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrivateRoom', [$privateRoom]);

        return parent::setPrivateRoom($privateRoom);
    }

    /**
     * {@inheritDoc}
     */
    public function isTelevision(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isTelevision', []);

        return parent::isTelevision();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelevision(?bool $television): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelevision', [$television]);

        return parent::setTelevision($television);
    }

    /**
     * {@inheritDoc}
     */
    public function isWifi(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isWifi', []);

        return parent::isWifi();
    }

    /**
     * {@inheritDoc}
     */
    public function setWifi(?bool $wifi): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWifi', [$wifi]);

        return parent::setWifi($wifi);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiet(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiet', []);

        return parent::getDiet();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiet(?string $diet): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiet', [$diet]);

        return parent::setDiet($diet);
    }

    /**
     * {@inheritDoc}
     */
    public function getPatients(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatients', []);

        return parent::getPatients();
    }

}
