<?php

namespace ContainerUL3ZFNP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppointmentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6rDw3zv.App\Entity\Appointment' shared service.
     *
     * @return \App\Entity\Appointment
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6rDw3zv": it references class "App\\Entity\\Appointment" but no such service exists.');
    }
}
