<?php

namespace ContainerM6jcavi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6rDw3zvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6rDw3zv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6rDw3zv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'appointment' => ['privates', '.errored..service_locator.6rDw3zv.App\\Entity\\Appointment', NULL, 'Cannot autowire service ".service_locator.6rDw3zv": it references class "App\\Entity\\Appointment" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'appointment' => 'App\\Entity\\Appointment',
            'em' => '?',
        ]);
    }
}
