parameters:
    # paramètres globaux

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Security\LoginFailureHandler:
        public: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            
    App\Controller\DocumentController:
        arguments:
            $projectDir: '%kernel.project_dir%'