<?php

namespace Container2iGBZ3L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6XoJkW6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6XoJkW6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6XoJkW6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctorRepo' => ['privates', 'App\\Repository\\DoctorRepository', 'getDoctorRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'patientRepo' => ['privates', 'App\\Repository\\PatientRepository', 'getPatientRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
            'treatmentRepo' => ['privates', 'App\\Repository\\TreatmentRepository', 'getTreatmentRepositoryService', true],
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
        ], [
            'doctorRepo' => 'App\\Repository\\DoctorRepository',
            'em' => '?',
            'patientRepo' => 'App\\Repository\\PatientRepository',
            'serializer' => '?',
            'treatmentRepo' => 'App\\Repository\\TreatmentRepository',
            'urlGenerator' => '?',
        ]);
    }
}
