<?php

namespace ContainerIgW0ATk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4_BtIBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4.bt_iB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4.bt_iB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctorRepo' => ['privates', 'App\\Repository\\DoctorRepository', 'getDoctorRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'patientRepo' => ['privates', 'App\\Repository\\PatientRepository', 'getPatientRepositoryService', true],
            'treatmentRepo' => ['privates', 'App\\Repository\\TreatmentRepository', 'getTreatmentRepositoryService', true],
        ], [
            'doctorRepo' => 'App\\Repository\\DoctorRepository',
            'em' => '?',
            'patientRepo' => 'App\\Repository\\PatientRepository',
            'treatmentRepo' => 'App\\Repository\\TreatmentRepository',
        ]);
    }
}
