<?php

namespace ContainerIgW0ATk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OKls3RVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oKls3RV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oKls3RV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AppointmentController::bookAppointment' => ['privates', '.service_locator.4.bt_iB', 'get_ServiceLocator_4_BtIBService', true],
            'App\\Controller\\AppointmentController::comingAppointment' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\AppointmentController::pastAppointment' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\AppointmentSlotController::allDoctorsSlots' => ['privates', '.service_locator.sBfBVSt', 'get_ServiceLocator_SBfBVStService', true],
            'App\\Controller\\AppointmentSlotController::appointmentChange' => ['privates', '.service_locator.HiZqKKw', 'get_ServiceLocator_HiZqKKwService', true],
            'App\\Controller\\AppointmentSlotController::appointmentResults' => ['privates', '.service_locator.HiZqKKw', 'get_ServiceLocator_HiZqKKwService', true],
            'App\\Controller\\AppointmentSlotController::slots' => ['privates', '.service_locator.ncuyKjX', 'get_ServiceLocator_NcuyKjXService', true],
            'App\\Controller\\CenterController::getCentersForMap' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\CenterController::searchCentersWhat' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\DoctorController::searchDoctors' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\PatientController::me' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\PrescriptionController::getPrescription' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\TreatmentController::listTreatments' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\AppointmentController:bookAppointment' => ['privates', '.service_locator.4.bt_iB', 'get_ServiceLocator_4_BtIBService', true],
            'App\\Controller\\AppointmentController:comingAppointment' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\AppointmentController:pastAppointment' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\AppointmentSlotController:allDoctorsSlots' => ['privates', '.service_locator.sBfBVSt', 'get_ServiceLocator_SBfBVStService', true],
            'App\\Controller\\AppointmentSlotController:appointmentChange' => ['privates', '.service_locator.HiZqKKw', 'get_ServiceLocator_HiZqKKwService', true],
            'App\\Controller\\AppointmentSlotController:appointmentResults' => ['privates', '.service_locator.HiZqKKw', 'get_ServiceLocator_HiZqKKwService', true],
            'App\\Controller\\AppointmentSlotController:slots' => ['privates', '.service_locator.ncuyKjX', 'get_ServiceLocator_NcuyKjXService', true],
            'App\\Controller\\CenterController:getCentersForMap' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\CenterController:searchCentersWhat' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\DoctorController:searchDoctors' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\PatientController:me' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\PrescriptionController:getPrescription' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\TreatmentController:listTreatments' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\AppointmentController::bookAppointment' => '?',
            'App\\Controller\\AppointmentController::comingAppointment' => '?',
            'App\\Controller\\AppointmentController::pastAppointment' => '?',
            'App\\Controller\\AppointmentSlotController::allDoctorsSlots' => '?',
            'App\\Controller\\AppointmentSlotController::appointmentChange' => '?',
            'App\\Controller\\AppointmentSlotController::appointmentResults' => '?',
            'App\\Controller\\AppointmentSlotController::slots' => '?',
            'App\\Controller\\CenterController::getCentersForMap' => '?',
            'App\\Controller\\CenterController::searchCentersWhat' => '?',
            'App\\Controller\\DoctorController::searchDoctors' => '?',
            'App\\Controller\\PatientController::me' => '?',
            'App\\Controller\\PrescriptionController::getPrescription' => '?',
            'App\\Controller\\TreatmentController::listTreatments' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AppointmentController:bookAppointment' => '?',
            'App\\Controller\\AppointmentController:comingAppointment' => '?',
            'App\\Controller\\AppointmentController:pastAppointment' => '?',
            'App\\Controller\\AppointmentSlotController:allDoctorsSlots' => '?',
            'App\\Controller\\AppointmentSlotController:appointmentChange' => '?',
            'App\\Controller\\AppointmentSlotController:appointmentResults' => '?',
            'App\\Controller\\AppointmentSlotController:slots' => '?',
            'App\\Controller\\CenterController:getCentersForMap' => '?',
            'App\\Controller\\CenterController:searchCentersWhat' => '?',
            'App\\Controller\\DoctorController:searchDoctors' => '?',
            'App\\Controller\\PatientController:me' => '?',
            'App\\Controller\\PrescriptionController:getPrescription' => '?',
            'App\\Controller\\TreatmentController:listTreatments' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
