<?php

namespace ContainerIgW0ATk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HiZqKKwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HiZqKKw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HiZqKKw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'slotService' => ['privates', 'App\\Service\\SlotGeneratorService', 'getSlotGeneratorServiceService', true],
        ], [
            'doctrine' => '?',
            'slotService' => 'App\\Service\\SlotGeneratorService',
        ]);
    }
}
