<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPmq0mWs\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPmq0mWs/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerPmq0mWs.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerPmq0mWs\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerPmq0mWs\App_KernelTestDebugContainer([
    'container.build_hash' => 'Pmq0mWs',
    'container.build_id' => 'b3f85478',
    'container.build_time' => 1774260534,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPmq0mWs');
