<?php

namespace Container35xieBR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NinRdodService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ninRdod' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ninRdod'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'alarmRepo' => ['privates', 'App\\Repository\\AlarmRepository', 'getAlarmRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'alarmRepo' => 'App\\Repository\\AlarmRepository',
            'em' => '?',
        ]);
    }
}
