<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXfSzPZN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXfSzPZN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXfSzPZN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXfSzPZN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXfSzPZN\App_KernelDevDebugContainer([
    'container.build_hash' => 'XfSzPZN',
    'container.build_id' => '3a1ecc37',
    'container.build_time' => 1764792400,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXfSzPZN');
