<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM6jcavi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM6jcavi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM6jcavi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM6jcavi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM6jcavi\App_KernelDevDebugContainer([
    'container.build_hash' => 'M6jcavi',
    'container.build_id' => '5210a0cc',
    'container.build_time' => 1765723122,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM6jcavi');
