<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHFlxuz9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHFlxuz9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHFlxuz9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHFlxuz9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHFlxuz9\App_KernelDevDebugContainer([
    'container.build_hash' => 'HFlxuz9',
    'container.build_id' => '43b62d61',
    'container.build_time' => 1764548729,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHFlxuz9');
