<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_appointment_coming' => [[], ['_controller' => 'App\\Controller\\AppointmentController::comingAppointment'], [], [['text', '/api/appointment/coming']], [], [], []],
    'api_appointment_past' => [[], ['_controller' => 'App\\Controller\\AppointmentController::pastAppointment'], [], [['text', '/api/appointment/past']], [], [], []],
    'api_appointment_create' => [[], ['_controller' => 'App\\Controller\\AppointmentController::bookAppointment'], [], [['text', '/api/appointment/create']], [], [], []],
    'doctor_slots' => [['id'], ['_controller' => 'App\\Controller\\AppointmentSlotController::slots'], [], [['text', '/slots'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/doctor']], [], [], []],
    'all_doctors_slots' => [[], ['_controller' => 'App\\Controller\\AppointmentSlotController::allDoctorsSlots'], [], [['text', '/api/all-doctors/slots']], [], [], []],
    'api_appointment_change' => [[], ['_controller' => 'App\\Controller\\AppointmentSlotController::appointmentChange'], [], [['text', '/api/appointment/change']], [], [], []],
    'api_appointment_update' => [['id'], ['_controller' => 'App\\Controller\\AppointmentSlotController::updateAppointment'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/appointment/change']], [], [], []],
    'api_appointment_results' => [[], ['_controller' => 'App\\Controller\\AppointmentSlotController::results'], [], [['text', '/api/appointment/results']], [], [], []],
    'api_appointment_cancel' => [['id'], ['_controller' => 'App\\Controller\\AppointmentSlotController::cancelAppointment'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/appointment/cancel']], [], [], []],
    'api_centers_search' => [[], ['_controller' => 'App\\Controller\\CenterController::searchCentersWhat'], [], [['text', '/api/centers/search']], [], [], []],
    'api_centers_map' => [[], ['_controller' => 'App\\Controller\\CenterController::getCentersForMap'], [], [['text', '/api/centers/map']], [], [], []],
    'api_doctors_search' => [[], ['_controller' => 'App\\Controller\\DoctorController::searchDoctors'], [], [['text', '/api/doctors/search']], [], [], []],
    'api_login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/api/login']], [], [], []],
    'api_patient_medicalRecord' => [[], ['_controller' => 'App\\Controller\\PatientController::me'], [], [['text', '/api/patient/medicalRecord']], [], [], []],
    'api_registration' => [[], ['_controller' => 'App\\Controller\\PatientController::registration'], [], [['text', '/api/registration']], [], [], []],
    'api_prescription' => [[], ['_controller' => 'App\\Controller\\PrescriptionController::getPrescription'], [], [['text', '/api/prescription']], [], [], []],
    'api_treatments_list' => [[], ['_controller' => 'App\\Controller\\TreatmentController::listTreatments'], [], [['text', '/api/treatments/list']], [], [], []],
];
