<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'patients' => [[], ['_controller' => 'App\\Controller\\HealthNorthController::getPatientList'], [], [['text', '/healthnorth/api/patients']], [], [], []],
    'patient' => [['id'], ['_controller' => 'App\\Controller\\HealthNorthController::getPatient'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/healthnorth/api/patients']], [], [], []],
    'patientName' => [['id'], ['_controller' => 'App\\Controller\\HealthNorthController::getPatientName'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/healthnorth/api/patient']], [], [], []],
    'payment' => [['id'], ['_controller' => 'App\\Controller\\HealthNorthController::getPayment'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/healthnorth/api/payments']], [], [], []],
    'deletePayment' => [['id'], ['_controller' => 'App\\Controller\\HealthNorthController::deletePayment'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/healthnorth/api/payments']], [], [], []],
    'createPayment' => [[], ['_controller' => 'App\\Controller\\HealthNorthController::createPayment'], [], [['text', '/healthnorth/api/payments']], [], [], []],
    'updatePayment' => [['id'], ['_controller' => 'App\\Controller\\HealthNorthController::updatePayment'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/healthnorth/api/payments']], [], [], []],
    'api_login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/api/login']], [], [], []],
    'api_patient_me' => [[], ['_controller' => 'App\\Controller\\PatientController::me'], [], [['text', '/api/patient/me']], [], [], []],
    'api_patient_update' => [[], ['_controller' => 'App\\Controller\\PatientController::update'], [], [['text', '/api/patient/me']], [], [], []],
];
